### PR TITLE
Replace currying and and uncurrying functions with dynamic implementa…

### PR DESCRIPTION
**Pull request by yangzai**
…tions.

**Description of the change**

Replaces `mkFn`/`runFn` FFIs with more scalable dynamic implementations.

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [x] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by garyb** [comment]
Thanks for the PR, but what's the thinking behind this - just to cut down on the "dumbness" of the implementation, or does it perform better than the explicit implementations? If so, can you provide a benchmark please. 🙂

**Comment by yangzai** [comment]
@garyb mainly just to reduce LOC. I'm not sure if it's optimal but I can look into benchmarking and optimisation.

**Comment by yangzai** [comment]
@garyb some simple benchmarking with alternative implementations: https://gist.github.com/yangzai/5fd62a13c9281b76878659a1b94d4885. I don't think the performance drop can be justified so I should probably close this.

**Comment by garyb** [comment]
Thanks for following up! Yeah, I think we'll keep them as they are then - this is potentially a slightly performance-sensitive area. Mostly the intended use case for these is when the `runFn` stuff is fully saturated and the compiler optimises the intermediate calls away, but when that's not the case we'd still want minimal overhead.

**Pull request closed without merging**
